//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderArchive
    {
        public int Order__ID { get; set; }
        public int Product_ID { get; set; }
        public decimal OrderPrice { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
